[tool.black]
line-length = 80
py36 = true
target-version = ['py37']

[tool.isort]
combine_star = true
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 80
lines_after_imports = 2
multi_line_output = 3
use_parentheses = true
